<img src="../assets/ga-logo.png" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a dataset at a high level with `pandas`.

### Notebook Guide
An exercise in practising:

- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Writing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

### Business question

What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

#### 1. Import `pandas` and read in the LEGO dataset

In [3]:
import pandas as pd

#### 2. So we can focus on just the columns that help answer the question, select only the following columns into a new `DataFrame` variable:

- name
- theme
- number of pieces
- retail price (USD_MSRP)

In [4]:
df = pd.read_csv('./data/lego.csv', encoding='latin-1')
DataFrame = df[['Name', 'Theme', 'Pieces', 'USD_MSRP']]

#### 3. How many sets have a price greater than $100?

In [5]:
DataFrame[DataFrame['USD_MSRP'] > 100]['USD_MSRP'].count()

np.int64(380)

#### 4. What are the top 10 sets with the highest number of pieces?

In [6]:
DataFrame.sort_values(by='Pieces', ascending=False).head(10)

                                   Name           Theme   Pieces  USD_MSRP
13559                         World Map             Art  11695.0    249.99
13946                      Eiffel Tower           Icons  10001.0    629.99
13449                           Titanic           Icons   9090.0    679.99
12942                         Colosseum           Icons   9036.0    549.99
11928                 Millennium Falcon       Star Wars   7541.0    849.99
14380                   The Razor Crest       Star Wars   6187.0    599.99
14440  The Lord of the Rings: Rivendell           Icons   6167.0    499.99
14807              NINJAGO City Markets         Ninjago   6163.0    369.99
12369                   Hogwarts Castle    Harry Potter   6020.0    469.99
11437                         Taj Mahal  Creator Expert   5923.0    369.99

#### 5. Create a new column to measure "price per piece", which should be the price (USD_MSRP) divided by the number of pieces

In [11]:
# .copy() creates an independent copy of the filtered DataFrame,
# so changes to valid_sets will not affect the original DataFrame.
# cleaning the data for doesn't print 'inf' value in Price_per_Piece
valid_sets = DataFrame[DataFrame['Pieces'] > 0].copy()

valid_sets['Price_per_Piece'] = valid_sets['USD_MSRP'] / valid_sets['Pieces']

# Add the new colmuns with valid values 
DataFrame['Price_per_Piece'] = valid_sets['Price_per_Piece']

#### 6. Use this column to find the top 10 most expensive sets by "price per piece"

In [12]:
DataFrame.sort_values(by='Price_per_Piece', ascending=False).head(10)

,Name,Theme,Pieces,USD_MSRP,Price_per_Piece
9653,EV3 Intelligent Brick,Mindstorms,1.0,224.95,224.950
6342,NXT Intelligent Brick,Mindstorms,1.0,169.99,169.990
7695,Intelligent NXT Brick (Black),Mindstorms,1.0,169.99,169.990
13755,Small Hub,Education,2.0,214.95,107.475
9654,DC Rechargeable Battery,Education,1.0,99.95,99.950
8197,NXT DC Rechargeable Battery,Education,1.0,79.99,79.990
12927,Boost Hub,Powered Up,1.0,79.99,79.990
13756,Small Hub Battery,Education,1.0,69.95,69.950
8898,Accelerometer Sensor,Mindstorms,1.0,54.99,54.990
6976,Accelerometer Sensor for Mindstorms NXT,Mindstorms,1.0,54.99,54.990

#### 7. Narrow the search to show the top 10 most expensive sets by "price per piece" for the "Icons" theme *only*

In [14]:
DataFrame[DataFrame['Theme'] == 'Icons'].sort_values(by='Price_per_Piece', ascending=False).head(10)

,Name,Theme,Pieces,USD_MSRP,Price_per_Piece
13941,Optimus Prime,Icons,1508.0,179.99,0.119357
13943,Chevrolet Camaro Z/28 1969,Icons,1456.0,169.99,0.116751
13450,Porsche 911,Icons,1458.0,169.99,0.116591
13440,Adidas Originals Superstar,Icons,731.0,79.99,0.109425
13939,Back to the Future Time Machine,Icons,1872.0,199.99,0.106832
13942,Loop Coaster,Icons,3756.0,399.99,0.106494
14441,Land Rover Classic Defender 90,Icons,2336.0,239.99,0.102735
13446,Queer Eye â The Fab 5 Loft,Icons,974.0,99.99,0.102659
12940,Ghostbusters ECTO-1,Icons,2352.0,239.99,0.102037
13617,Everyone is Awesome,Icons,346.0,34.99,0.101127

#### 8. What are the top 10 cheapest sets by "price per piece" in the "Icons" theme?

In [15]:
DataFrame[DataFrame['Theme'] == 'Icons'].sort_values(by='Price_per_Piece').head(10)

,Name,Theme,Pieces,USD_MSRP,Price_per_Piece
13439,Bonsai Tree,Icons,878.0,49.99,0.056936
14576,Daffodils,Icons,216.0,12.99,0.060139
12942,Colosseum,Icons,9036.0,549.99,0.060867
14438,Dried Flower Centrepiece,Icons,812.0,49.99,0.061564
13946,Eiffel Tower,Icons,10001.0,629.99,0.062993
13443,Camp Nou - FC Barcelona,Icons,5509.0,349.99,0.063531
14437,Wildflower Bouquet,Icons,939.0,59.99,0.063887
13948,Succulents,Icons,771.0,49.99,0.064838
13947,Holiday Main Street,Icons,1514.0,99.99,0.066044
13938,Real Madrid - Santiago BernabÃ©u Stadium,Icons,5876.0,399.99,0.068072

#### 9. Export the `DataFrame` you created in question 2. to a new CSV file.

In [16]:
DataFrame.to_csv('lego_filtered.csv', index=False)

### Reflection

What is your answer to the business question? Here it is as a reminder:

> What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

Reflect on your experience. How was working with `pandas` compared to other tools you already know?